- ros_topic_name: /singulator/cell/r12_c00/cmd_vel
  gz_topic_name: /singulator/cell/r12_c00/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r12_c01/cmd_vel
  gz_topic_name: /singulator/cell/r12_c01/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r12_c02/cmd_vel
  gz_topic_name: /singulator/cell/r12_c02/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r12_c03/cmd_vel
  gz_topic_name: /singulator/cell/r12_c03/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r13_c00/cmd_vel
  gz_topic_name: /singulator/cell/r13_c00/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r13_c01/cmd_vel
  gz_topic_name: /singulator/cell/r13_c01/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r13_c02/cmd_vel
  gz_topic_name: /singulator/cell/r13_c02/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /singulator/cell/r13_c03/cmd_vel
  gz_topic_name: /singulator/cell/r13_c03/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
